/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clasesjava.vista;

import com.mycompany.clasesjava.modelo.Cliente;
import com.mycompany.clasesjava.modelo.Empleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author 1214k
 */
public class Form extends javax.swing.JFrame implements ActionListener{

    List<Cliente> listaClientes;
    List<Empleado> listaEmpleados;
    
    public Form() {
        initComponents();
        btnGuardarCliente.addActionListener(this);
        btnConsultarCliente.addActionListener(this);
        btnGuardarempleado.addActionListener(this);
        btnConsultarEmpleado.addActionListener(this);
        
        listaClientes = new ArrayList<>();
        listaEmpleados = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDcliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDicCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSaldoCliente = new javax.swing.JTextField();
        btnConsultarCliente = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDempleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreempleado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellidoempleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDicempleado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelempleado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCodempleado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSalarioempleado = new javax.swing.JTextField();
        txtPuestoempleado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnGuardarempleado = new javax.swing.JButton();
        btnConsultarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO Y CONSULTA DE UN CLIENTE");

        jLabel2.setText("CODIGO:");

        jLabel4.setText("ID:");

        jLabel5.setText("NOMBRE:");

        jLabel6.setText("APELLIDO:");

        jLabel7.setText("DIRECCION:");

        jLabel8.setText("TELEFONO:");

        jLabel9.setText("SALDO:");

        btnConsultarCliente.setText("CONSULTAR");

        btnGuardarCliente.setText("GUARDAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDicCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnConsultarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarCliente)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDicCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSaldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarCliente)
                    .addComponent(btnGuardarCliente))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLIENTE", jPanel1);

        jLabel3.setText("EMPLEADO");

        jLabel10.setText("ID:");

        jLabel11.setText("NOMBRE:");

        jLabel12.setText("APELLIDO:");

        jLabel13.setText("DIRECCION:");

        jLabel14.setText("TELEFONO:");

        jLabel15.setText("CODIGO:");

        jLabel16.setText("SALDO:");

        jLabel17.setText("PUESTO:");

        btnGuardarempleado.setText("Guardar Empleado");

        btnConsultarEmpleado.setText("Consultar Empleado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDicempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuestoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardarempleado))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarEmpleado)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalarioempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtApellidoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtDicempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTelempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSalarioempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtPuestoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarempleado)
                    .addComponent(btnConsultarEmpleado))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EMPLEADO", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarEmpleado;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoempleado;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodempleado;
    private javax.swing.JTextField txtDicCliente;
    private javax.swing.JTextField txtDicempleado;
    private javax.swing.JTextField txtIDcliente;
    private javax.swing.JTextField txtIDempleado;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreempleado;
    private javax.swing.JTextField txtPuestoempleado;
    private javax.swing.JTextField txtSalarioempleado;
    private javax.swing.JTextField txtSaldoCliente;
    private javax.swing.JTextField txtTelCliente;
    private javax.swing.JTextField txtTelempleado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    
        if(e.getSource() == btnGuardarCliente){
            String registroClientes = "RegistroClientes";
            listaClientes.add(new Cliente(Integer.parseInt(txtIDcliente.getText()), 
                    txtNombreCliente.getText(), txtApellidoCliente.getText(), txtDicCliente.getText(), Integer.parseInt(txtTelCliente.getText()), 
                    Integer.parseInt(txtCodCliente.getText()), Integer.parseInt(txtSaldoCliente.getText())));
        
            //Creamos la variable writer de la Clase BufferdWriter que es una clase para escribir en archivos
        //write recibe el parametro de new FileWrite, donde especificamos el nombre del archivo a escribir
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(registroClientes, true))) {
            for (Cliente cliente : listaClientes) { //Recorremos todos los datos de la lista de ventas
                //Cadena para representar los registros actuales
                String registro = cliente.getId() + "-" + cliente.getNombre() +"-"+cliente.getApellido() + "-" + cliente.getDireccion() +"-"+
                        cliente.getTelefono() + "-" + cliente.getCodigo() +"-"+cliente.getSaldo();
                
                
                    writer.write(registro);
                    writer.newLine();
                
            }
            System.out.println("Registro de ventas guardado en " + registroClientes);
        } catch (IOException a) {
            System.err.println("Error al guardar el registro de ventas: " + a.getMessage());
        }
        }
        if(e.getSource() == btnGuardarempleado){
            String registroEmpleados = "RegistroEmpleados";
            listaEmpleados.add(new Empleado(Integer.parseInt(txtIDempleado.getText()), 
                    txtNombreempleado.getText(), txtApellidoempleado.getText(), txtDicempleado.getText(), Integer.parseInt(txtTelempleado.getText()), 
                    Integer.parseInt(txtCodempleado.getText()), txtPuestoempleado.getText() ,Integer.parseInt(txtSalarioempleado.getText())));
        
            //Creamos la variable writer de la Clase BufferdWriter que es una clase para escribir en archivos
        //write recibe el parametro de new FileWrite, donde especificamos el nombre del archivo a escribir
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(registroEmpleados, true))) {
            for (Empleado empleado : listaEmpleados) { //Recorremos todos los datos de la lista de ventas
                //Cadena para representar los registros actuales
                String registro = empleado.getId() + "-" + empleado.getNombre() +"-"+empleado.getApellido() + "-" + empleado.getDireccion() +"-"+
                        empleado.getTelefono() + "-" + empleado.getCodigo() +"-"+empleado.getPuesto()+"-"+empleado.getSalario();
                
                
                    writer.write(registro);
                    writer.newLine();
                
            }
            System.out.println("Registro de ventas guardado en " + registroEmpleados);
        } catch (IOException a) {
            System.err.println("Error al guardar el registro de ventas: " + a.getMessage());
        }
        }
        if(e.getSource() == btnConsultarCliente){
            String registroClientes = "RegistroClientes";
            try (BufferedReader br = new BufferedReader(new FileReader(registroClientes))) {
            String line; //Para almacenar una linea del archivo de texto
            while ((line = br.readLine()) != null) { //Line es igual a la linea del archivo que no este vacia
                System.out.println(line);; //guardamos cada linea en la lista de los registros ya existentes
            }
        } catch (IOException b) { //En caso de haber un error
            b.printStackTrace();
        }
        }
        if(e.getSource() == btnConsultarEmpleado){
            String registroEmpleados = "RegistroEmpleados";
            try (BufferedReader br = new BufferedReader(new FileReader(registroEmpleados))) {
            String line; //Para almacenar una linea del archivo de texto
            while ((line = br.readLine()) != null) { //Line es igual a la linea del archivo que no este vacia
                System.out.println(line);; //guardamos cada linea en la lista de los registros ya existentes
            }
        } catch (IOException b) { //En caso de haber un error
            b.printStackTrace();
        }
        }
        
    
    }
}
